POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Python",
    "author": "Guido van Rossum",
    "url": "https://blog.dropbox.com/topics/work-culture/-the-mind-at-work--guido-van-rossum-on-how-python-makes-thinking",
    "likes": 201
}